// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqGetHotBlog struct {
	Current int64 `form:"current,default=1"`
}

type ReqGetMyBlog struct {
	Current int64 `form:"current,default=1"`
}

type ReqInsertBlog struct {
	Blog Blog `json:"blog"`
}

type ReqLikeBlog struct {
	BlogId int64 `json:"blog_id"`
}

type RespGetHotBlog struct {
	BlogList []Blog `json:"blog_list"`
}

type RespGetMyBlog struct {
	BlogList []Blog `json:"blog_list"`
}

type RespInsertBlog struct {
	Id int64 `path:"id"`
}

type RespLikeBlog struct {
}
