// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqGetShopById struct {
	Id uint64 `path:"id"`
}

type ReqGetShopByName struct {
	Name    string `form:"name,optional"`
	Current int64  `form:"current,default=1"`
}

type ReqGetShopByType struct {
	TypeId  int64 `form:"typeId"`
	Current int64 `form:"current,default=1"`
}

type ReqInsertShop struct {
	Shop Shop `json:"shop"`
}

type ReqUpdateShop struct {
	Shop Shop `json:"shop"`
}

type RespGetShopById struct {
	Shop Shop `json:"shop"`
}

type RespGetShopByName struct {
	ShopList []Shop `json:"shop_list"`
}

type RespGetShopByType struct {
	ShopList []Shop `json:"shop_list"`
}

type RespInsertShop struct {
	Id int64 `path:"id"`
}

type RespUpdateShop struct {
}
