// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Blog struct {
	Id       int64  `json:"id"`
	ShopId   int64  `json:"shop_id"`
	UserId   int64  `json:"user_id"`
	Title    string `json:"title"`
	Images   string `json:"images"` // separated by comma
	Content  string `json:"content"`
	Liked    int64  `json:"liked"`
	Comments int64  `json:"comments"`
}

type Shop struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	TypeId    int64   `json:"type_id"`
	Images    string  `json:"images"` // separated by comma
	Area      string  `json:"area"`
	Address   string  `json:"address"`
	X         float64 `json:"x"`
	Y         float64 `json:"y"`
	AvgPrice  int64   `json:"avg_price"`
	Sold      int32   `json:"sold"`
	Comments  int32   `json:"comments"`
	Score     int32   `json:"score"`      // 1-5
	OpenHours string  `json:"open_hours"` // such as 10:00-22:00
}

type ShopType struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"` // icon url
	Sort int64  `json:"sort"` // sort by this field
}

type Voucher struct {
	Id          int64  `json:"id"`
	ShopId      int64  `json:"shop_id"`
	Title       string `json:"title"`
	Subtitle    string `json:"subtitle"`
	Rules       string `json:"rules"`
	PayPrice    int64  `json:"pay_price"`
	ActualPrice int64  `json:"actual_price"`
	Type        int32  `json:"type"`
	Status      int32  `json:"status"`
}
