// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqDeleteBlogImage struct {
	Name string `form:"name"`
}

type ReqUploadImage struct {
	File string `form:"file"`
}

type RespDeleteBlogImage struct {
}

type RespUploadImage struct {
}
