// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqGetInfo struct {
	Id int64 `path:"id"`
}

type ReqGetMe struct {
}

type ReqLogout struct {
}

type RespGetInfo struct {
	UserInfo struct {
		Id        int64  `json:"id"`
		City      string `json:"city"`
		Introduce string `json:"introduce"`
		Fans      int32  `json:"fans"`
		Followee  int32  `json:"followee"`
		Gender    bool   `json:"gender"`   // 0: male, 1: female
		Birthday  string `json:"birthday"` // YYYY-MM-DD
		Credit    int32  `json:"credit"`
		Level     bool   `json:"level"` // 0: normal, 1: vip
	}
}

type RespGetMe struct {
}

type RespLogout struct {
}
