// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type ReqLogin struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type ReqSendCode struct {
	Phone string `json:"phone"`
}

type RespLogin struct {
	Token string `json:"token"`
}

type RespSendCode struct {
	Code string `json:"code"`
}
