// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: shop.proto

package server

import (
	"context"

	"micro-ping/service/shop/internal/logic"
	"micro-ping/service/shop/internal/svc"
	"micro-ping/service/shop/shop"
)

type ShopSServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedShopSServer
}

func NewShopSServer(svcCtx *svc.ServiceContext) *ShopSServer {
	return &ShopSServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopSServer) GetShopById(ctx context.Context, in *shop.ReqGetShopById) (*shop.RespGetShopById, error) {
	l := logic.NewGetShopByIdLogic(ctx, s.svcCtx)
	return l.GetShopById(in)
}
