// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendCode
type ReqSendCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSendCode) Reset() {
	*x = ReqSendCode{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendCode) ProtoMessage() {}

func (x *ReqSendCode) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendCode.ProtoReflect.Descriptor instead.
func (*ReqSendCode) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSendCode) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type RespSendCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespSendCode) Reset() {
	*x = RespSendCode{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespSendCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSendCode) ProtoMessage() {}

func (x *RespSendCode) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSendCode.ProtoReflect.Descriptor instead.
func (*RespSendCode) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RespSendCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Login
type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ReqLogin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ReqLogin) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RespLogin) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Logout
type ReqLogout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogout) Reset() {
	*x = ReqLogout{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogout) ProtoMessage() {}

func (x *ReqLogout) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogout.ProtoReflect.Descriptor instead.
func (*ReqLogout) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type RespLogout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespLogout) Reset() {
	*x = RespLogout{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogout) ProtoMessage() {}

func (x *RespLogout) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogout.ProtoReflect.Descriptor instead.
func (*RespLogout) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

// GetMe
type ReqGetMe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetMe) Reset() {
	*x = ReqGetMe{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetMe) ProtoMessage() {}

func (x *ReqGetMe) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetMe.ProtoReflect.Descriptor instead.
func (*ReqGetMe) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ReqGetMe) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RespGetMe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespGetMe) Reset() {
	*x = RespGetMe{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetMe) ProtoMessage() {}

func (x *RespGetMe) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetMe.ProtoReflect.Descriptor instead.
func (*RespGetMe) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RespGetMe) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RespGetMe) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RespGetMe) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

// GetInfo
type ReqGetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetInfo) Reset() {
	*x = ReqGetInfo{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetInfo) ProtoMessage() {}

func (x *ReqGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetInfo.ProtoReflect.Descriptor instead.
func (*ReqGetInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ReqGetInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Introduce     string                 `protobuf:"bytes,3,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Fans          int32                  `protobuf:"varint,4,opt,name=fans,proto3" json:"fans,omitempty"`
	Followee      int32                  `protobuf:"varint,5,opt,name=followee,proto3" json:"followee,omitempty"`
	Gender        bool                   `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday      string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Credit        int32                  `protobuf:"varint,8,opt,name=credit,proto3" json:"credit,omitempty"`
	Level         bool                   `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserInfo) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *UserInfo) GetFans() int32 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *UserInfo) GetFollowee() int32 {
	if x != nil {
		return x.Followee
	}
	return 0
}

func (x *UserInfo) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

func (x *UserInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserInfo) GetCredit() int32 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *UserInfo) GetLevel() bool {
	if x != nil {
		return x.Level
	}
	return false
}

type RespGetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespGetInfo) Reset() {
	*x = RespGetInfo{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetInfo) ProtoMessage() {}

func (x *RespGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetInfo.ProtoReflect.Descriptor instead.
func (*RespGetInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *RespGetInfo) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"#\n" +
	"\vReqSendCode\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"\"\n" +
	"\fRespSendCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"4\n" +
	"\bReqLogin\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"$\n" +
	"\tRespLogin\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\v\n" +
	"\tReqLogout\"\f\n" +
	"\n" +
	"RespLogout\"#\n" +
	"\bReqGetMe\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"Q\n" +
	"\tRespGetMe\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"\x1c\n" +
	"\n" +
	"ReqGetInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xde\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1c\n" +
	"\tintroduce\x18\x03 \x01(\tR\tintroduce\x12\x12\n" +
	"\x04fans\x18\x04 \x01(\x05R\x04fans\x12\x1a\n" +
	"\bfollowee\x18\x05 \x01(\x05R\bfollowee\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\bR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x16\n" +
	"\x06credit\x18\b \x01(\x05R\x06credit\x12\x14\n" +
	"\x05level\x18\t \x01(\bR\x05level\"9\n" +
	"\vRespGetInfo\x12*\n" +
	"\buserInfo\x18\x01 \x01(\v2\x0e.user.UserInfoR\buserInfo2\xec\x01\n" +
	"\x04User\x121\n" +
	"\bSendCode\x12\x11.user.ReqSendCode\x1a\x12.user.RespSendCode\x12(\n" +
	"\x05Login\x12\x0e.user.ReqLogin\x1a\x0f.user.RespLogin\x12-\n" +
	"\bLoginOut\x12\x0f.user.ReqLogout\x1a\x10.user.RespLogout\x12(\n" +
	"\x05GetMe\x12\x0e.user.ReqGetMe\x1a\x0f.user.RespGetMe\x12.\n" +
	"\aGetInfo\x12\x10.user.ReqGetInfo\x1a\x11.user.RespGetInfoB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*ReqSendCode)(nil),  // 0: user.ReqSendCode
	(*RespSendCode)(nil), // 1: user.RespSendCode
	(*ReqLogin)(nil),     // 2: user.ReqLogin
	(*RespLogin)(nil),    // 3: user.RespLogin
	(*ReqLogout)(nil),    // 4: user.ReqLogout
	(*RespLogout)(nil),   // 5: user.RespLogout
	(*ReqGetMe)(nil),     // 6: user.ReqGetMe
	(*RespGetMe)(nil),    // 7: user.RespGetMe
	(*ReqGetInfo)(nil),   // 8: user.ReqGetInfo
	(*UserInfo)(nil),     // 9: user.UserInfo
	(*RespGetInfo)(nil),  // 10: user.RespGetInfo
}
var file_user_proto_depIdxs = []int32{
	9,  // 0: user.RespGetInfo.userInfo:type_name -> user.UserInfo
	0,  // 1: user.User.SendCode:input_type -> user.ReqSendCode
	2,  // 2: user.User.Login:input_type -> user.ReqLogin
	4,  // 3: user.User.LoginOut:input_type -> user.ReqLogout
	6,  // 4: user.User.GetMe:input_type -> user.ReqGetMe
	8,  // 5: user.User.GetInfo:input_type -> user.ReqGetInfo
	1,  // 6: user.User.SendCode:output_type -> user.RespSendCode
	3,  // 7: user.User.Login:output_type -> user.RespLogin
	5,  // 8: user.User.LoginOut:output_type -> user.RespLogout
	7,  // 9: user.User.GetMe:output_type -> user.RespGetMe
	10, // 10: user.User.GetInfo:output_type -> user.RespGetInfo
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
