// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: shop.proto

package shop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopS_GetShopById_FullMethodName = "/shop.ShopS/GetShopById"
)

// ShopSClient is the client API for ShopS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopSClient interface {
	GetShopById(ctx context.Context, in *ReqGetShopById, opts ...grpc.CallOption) (*RespGetShopById, error)
}

type shopSClient struct {
	cc grpc.ClientConnInterface
}

func NewShopSClient(cc grpc.ClientConnInterface) ShopSClient {
	return &shopSClient{cc}
}

func (c *shopSClient) GetShopById(ctx context.Context, in *ReqGetShopById, opts ...grpc.CallOption) (*RespGetShopById, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespGetShopById)
	err := c.cc.Invoke(ctx, ShopS_GetShopById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopSServer is the server API for ShopS service.
// All implementations must embed UnimplementedShopSServer
// for forward compatibility.
type ShopSServer interface {
	GetShopById(context.Context, *ReqGetShopById) (*RespGetShopById, error)
	mustEmbedUnimplementedShopSServer()
}

// UnimplementedShopSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopSServer struct{}

func (UnimplementedShopSServer) GetShopById(context.Context, *ReqGetShopById) (*RespGetShopById, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopById not implemented")
}
func (UnimplementedShopSServer) mustEmbedUnimplementedShopSServer() {}
func (UnimplementedShopSServer) testEmbeddedByValue()               {}

// UnsafeShopSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopSServer will
// result in compilation errors.
type UnsafeShopSServer interface {
	mustEmbedUnimplementedShopSServer()
}

func RegisterShopSServer(s grpc.ServiceRegistrar, srv ShopSServer) {
	// If the following call pancis, it indicates UnimplementedShopSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopS_ServiceDesc, srv)
}

func _ShopS_GetShopById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetShopById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopSServer).GetShopById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopS_GetShopById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopSServer).GetShopById(ctx, req.(*ReqGetShopById))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopS_ServiceDesc is the grpc.ServiceDesc for ShopS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.ShopS",
	HandlerType: (*ShopSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShopById",
			Handler:    _ShopS_GetShopById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop.proto",
}
