// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: shop.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeId        uint64                 `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Images        string                 `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	Area          string                 `protobuf:"bytes,4,opt,name=area,proto3" json:"area,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	X             float64                `protobuf:"fixed64,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,7,opt,name=y,proto3" json:"y,omitempty"`
	AvgPrice      int64                  `protobuf:"varint,8,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Sold          uint64                 `protobuf:"varint,9,opt,name=sold,proto3" json:"sold,omitempty"`
	Comments      uint64                 `protobuf:"varint,10,opt,name=comments,proto3" json:"comments,omitempty"`
	Score         uint64                 `protobuf:"varint,11,opt,name=score,proto3" json:"score,omitempty"`
	OpenHours     string                 `protobuf:"bytes,12,opt,name=open_hours,json=openHours,proto3" json:"open_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shop) GetTypeId() uint64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Shop) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *Shop) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *Shop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Shop) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Shop) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Shop) GetAvgPrice() int64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Shop) GetSold() uint64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *Shop) GetComments() uint64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

func (x *Shop) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Shop) GetOpenHours() string {
	if x != nil {
		return x.OpenHours
	}
	return ""
}

type ReqGetShopById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetShopById) Reset() {
	*x = ReqGetShopById{}
	mi := &file_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetShopById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetShopById) ProtoMessage() {}

func (x *ReqGetShopById) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetShopById.ProtoReflect.Descriptor instead.
func (*ReqGetShopById) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetShopById) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RespGetShopById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespGetShopById) Reset() {
	*x = RespGetShopById{}
	mi := &file_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetShopById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetShopById) ProtoMessage() {}

func (x *RespGetShopById) ProtoReflect() protoreflect.Message {
	mi := &file_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetShopById.ProtoReflect.Descriptor instead.
func (*RespGetShopById) Descriptor() ([]byte, []int) {
	return file_shop_proto_rawDescGZIP(), []int{2}
}

func (x *RespGetShopById) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

var File_shop_proto protoreflect.FileDescriptor

const file_shop_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"shop.proto\x12\x04shop\"\x97\x02\n" +
	"\x04Shop\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\x04R\x06typeId\x12\x16\n" +
	"\x06images\x18\x03 \x01(\tR\x06images\x12\x12\n" +
	"\x04area\x18\x04 \x01(\tR\x04area\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\f\n" +
	"\x01x\x18\x06 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x01R\x01y\x12\x1b\n" +
	"\tavg_price\x18\b \x01(\x03R\bavgPrice\x12\x12\n" +
	"\x04sold\x18\t \x01(\x04R\x04sold\x12\x1a\n" +
	"\bcomments\x18\n" +
	" \x01(\x04R\bcomments\x12\x14\n" +
	"\x05score\x18\v \x01(\x04R\x05score\x12\x1d\n" +
	"\n" +
	"open_hours\x18\f \x01(\tR\topenHours\" \n" +
	"\x0eReqGetShopById\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"1\n" +
	"\x0fRespGetShopById\x12\x1e\n" +
	"\x04shop\x18\x01 \x01(\v2\n" +
	".shop.ShopR\x04shop2E\n" +
	"\x05ShopS\x12<\n" +
	"\vGetShopById\x12\x14.shop.ReqGetShopById\x1a\x15.shop.RespGetShopById\"\x00B\bZ\x06./shopb\x06proto3"

var (
	file_shop_proto_rawDescOnce sync.Once
	file_shop_proto_rawDescData []byte
)

func file_shop_proto_rawDescGZIP() []byte {
	file_shop_proto_rawDescOnce.Do(func() {
		file_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)))
	})
	return file_shop_proto_rawDescData
}

var file_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shop_proto_goTypes = []any{
	(*Shop)(nil),            // 0: shop.Shop
	(*ReqGetShopById)(nil),  // 1: shop.ReqGetShopById
	(*RespGetShopById)(nil), // 2: shop.RespGetShopById
}
var file_shop_proto_depIdxs = []int32{
	0, // 0: shop.RespGetShopById.shop:type_name -> shop.Shop
	1, // 1: shop.ShopS.GetShopById:input_type -> shop.ReqGetShopById
	2, // 2: shop.ShopS.GetShopById:output_type -> shop.RespGetShopById
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shop_proto_init() }
func file_shop_proto_init() {
	if File_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_proto_rawDesc), len(file_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_proto_goTypes,
		DependencyIndexes: file_shop_proto_depIdxs,
		MessageInfos:      file_shop_proto_msgTypes,
	}.Build()
	File_shop_proto = out.File
	file_shop_proto_goTypes = nil
	file_shop_proto_depIdxs = nil
}
