// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: shop_type.proto

package server

import (
	"context"

	"shop_type/internal/logic"
	"shop_type/internal/svc"
	"shop_type/shop_type"
)

type ShopTypeServer struct {
	svcCtx *svc.ServiceContext
	shop_type.UnimplementedShopTypeServer
}

func NewShopTypeServer(svcCtx *svc.ServiceContext) *ShopTypeServer {
	return &ShopTypeServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopTypeServer) GetTypeList(ctx context.Context, in *shop_type.ReqShopType) (*shop_type.RespShopType, error) {
	l := logic.NewGetTypeListLogic(ctx, s.svcCtx)
	return l.GetTypeList(in)
}
