// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: shop.proto

package shops

import (
	"context"

	"micro-ping/service/shop/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ReqGetShopById  = shop.ReqGetShopById
	RespGetShopById = shop.RespGetShopById
	Shop            = shop.Shop

	ShopS interface {
		GetShopById(ctx context.Context, in *ReqGetShopById, opts ...grpc.CallOption) (*RespGetShopById, error)
	}

	defaultShopS struct {
		cli zrpc.Client
	}
)

func NewShopS(cli zrpc.Client) ShopS {
	return &defaultShopS{
		cli: cli,
	}
}

func (m *defaultShopS) GetShopById(ctx context.Context, in *ReqGetShopById, opts ...grpc.CallOption) (*RespGetShopById, error) {
	client := shop.NewShopSClient(m.cli.Conn())
	return client.GetShopById(ctx, in, opts...)
}
