// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: shop_type.proto

package shop_type

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopType_GetTypeList_FullMethodName = "/shop_type.Shop_type/GetTypeList"
)

// ShopTypeClient is the client API for ShopType service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopTypeClient interface {
	GetTypeList(ctx context.Context, in *ReqShopType, opts ...grpc.CallOption) (*RespShopType, error)
}

type shopTypeClient struct {
	cc grpc.ClientConnInterface
}

func NewShopTypeClient(cc grpc.ClientConnInterface) ShopTypeClient {
	return &shopTypeClient{cc}
}

func (c *shopTypeClient) GetTypeList(ctx context.Context, in *ReqShopType, opts ...grpc.CallOption) (*RespShopType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespShopType)
	err := c.cc.Invoke(ctx, ShopType_GetTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopTypeServer is the server API for ShopType service.
// All implementations must embed UnimplementedShopTypeServer
// for forward compatibility.
type ShopTypeServer interface {
	GetTypeList(context.Context, *ReqShopType) (*RespShopType, error)
	mustEmbedUnimplementedShopTypeServer()
}

// UnimplementedShopTypeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopTypeServer struct{}

func (UnimplementedShopTypeServer) GetTypeList(context.Context, *ReqShopType) (*RespShopType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTypeList not implemented")
}
func (UnimplementedShopTypeServer) mustEmbedUnimplementedShopTypeServer() {}
func (UnimplementedShopTypeServer) testEmbeddedByValue()                  {}

// UnsafeShopTypeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopTypeServer will
// result in compilation errors.
type UnsafeShopTypeServer interface {
	mustEmbedUnimplementedShopTypeServer()
}

func RegisterShopTypeServer(s grpc.ServiceRegistrar, srv ShopTypeServer) {
	// If the following call pancis, it indicates UnimplementedShopTypeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopType_ServiceDesc, srv)
}

func _ShopType_GetTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqShopType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopTypeServer).GetTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopType_GetTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopTypeServer).GetTypeList(ctx, req.(*ReqShopType))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopType_ServiceDesc is the grpc.ServiceDesc for ShopType service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopType_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop_type.Shop_type",
	HandlerType: (*ShopTypeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTypeList",
			Handler:    _ShopType_GetTypeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop_type.proto",
}
