// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shop_type.proto

package shop_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int64                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopType) Reset() {
	*x = ShopType{}
	mi := &file_shop_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopType) ProtoMessage() {}

func (x *ShopType) ProtoReflect() protoreflect.Message {
	mi := &file_shop_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopType.ProtoReflect.Descriptor instead.
func (*ShopType) Descriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{0}
}

func (x *ShopType) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopType) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ShopType) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ReqShopType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqShopType) Reset() {
	*x = ReqShopType{}
	mi := &file_shop_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqShopType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqShopType) ProtoMessage() {}

func (x *ReqShopType) ProtoReflect() protoreflect.Message {
	mi := &file_shop_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqShopType.ProtoReflect.Descriptor instead.
func (*ReqShopType) Descriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{1}
}

type RespShopType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopTypeList  []*ShopType            `protobuf:"bytes,1,rep,name=shop_type_list,json=shopTypeList,proto3" json:"shop_type_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespShopType) Reset() {
	*x = RespShopType{}
	mi := &file_shop_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespShopType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespShopType) ProtoMessage() {}

func (x *RespShopType) ProtoReflect() protoreflect.Message {
	mi := &file_shop_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespShopType.ProtoReflect.Descriptor instead.
func (*RespShopType) Descriptor() ([]byte, []int) {
	return file_shop_type_proto_rawDescGZIP(), []int{2}
}

func (x *RespShopType) GetShopTypeList() []*ShopType {
	if x != nil {
		return x.ShopTypeList
	}
	return nil
}

var File_shop_type_proto protoreflect.FileDescriptor

const file_shop_type_proto_rawDesc = "" +
	"\n" +
	"\x0fshop_type.proto\x12\tshop_type\"V\n" +
	"\bShopType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x03R\x04sort\"\r\n" +
	"\vReqShopType\"I\n" +
	"\fRespShopType\x129\n" +
	"\x0eshop_type_list\x18\x01 \x03(\v2\x13.shop_type.ShopTypeR\fshopTypeList2K\n" +
	"\tShop_type\x12>\n" +
	"\vGetTypeList\x12\x16.shop_type.ReqShopType\x1a\x17.shop_type.RespShopTypeB\rZ\v./shop_typeb\x06proto3"

var (
	file_shop_type_proto_rawDescOnce sync.Once
	file_shop_type_proto_rawDescData []byte
)

func file_shop_type_proto_rawDescGZIP() []byte {
	file_shop_type_proto_rawDescOnce.Do(func() {
		file_shop_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_type_proto_rawDesc), len(file_shop_type_proto_rawDesc)))
	})
	return file_shop_type_proto_rawDescData
}

var file_shop_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shop_type_proto_goTypes = []any{
	(*ShopType)(nil),     // 0: shop_type.ShopType
	(*ReqShopType)(nil),  // 1: shop_type.ReqShopType
	(*RespShopType)(nil), // 2: shop_type.RespShopType
}
var file_shop_type_proto_depIdxs = []int32{
	0, // 0: shop_type.RespShopType.shop_type_list:type_name -> shop_type.ShopType
	1, // 1: shop_type.Shop_type.GetTypeList:input_type -> shop_type.ReqShopType
	2, // 2: shop_type.Shop_type.GetTypeList:output_type -> shop_type.RespShopType
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shop_type_proto_init() }
func file_shop_type_proto_init() {
	if File_shop_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_type_proto_rawDesc), len(file_shop_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_type_proto_goTypes,
		DependencyIndexes: file_shop_type_proto_depIdxs,
		MessageInfos:      file_shop_type_proto_msgTypes,
	}.Build()
	File_shop_type_proto = out.File
	file_shop_type_proto_goTypes = nil
	file_shop_type_proto_depIdxs = nil
}
