// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: user.proto

package server

import (
	"context"

	"micro-ping/service/user/internal/logic"
	"micro-ping/service/user/internal/svc"
	"micro-ping/service/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) SendCode(ctx context.Context, in *user.ReqSendCode) (*user.RespSendCode, error) {
	l := logic.NewSendCodeLogic(ctx, s.svcCtx)
	return l.SendCode(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.ReqLogin) (*user.RespLogin, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) LoginOut(ctx context.Context, in *user.ReqLogout) (*user.RespLogout, error) {
	l := logic.NewLoginOutLogic(ctx, s.svcCtx)
	return l.LoginOut(in)
}

func (s *UserServer) GetMe(ctx context.Context, in *user.ReqGetMe) (*user.RespGetMe, error) {
	l := logic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

func (s *UserServer) GetInfo(ctx context.Context, in *user.ReqGetInfo) (*user.RespGetInfo, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}
